W-14998627: Mule Application plugin with unresolved property should not fail
mulesoft/mule-maven-plugin pull request #818
Opened 2024-04-29 02:08 UTC by aguozden

When building with MMP and having a project that is considered an application (see asApplication) and is also a mule-plugin (see Classifier), the final application will set some variables when using this plugin.
Therefore no error should be caught when building with MMP.
An integration test was implemented that reproduces the Bug issue.

New bug for Runtime, to implement fix: [W-15556985](https://gus.lightning.force.com/a07EE00001pKJUKYA4)
New user.story for MMP to remove try-catch after Runtime fix: [W-15554719](https://gus.lightning.force.com/a07EE00001pJKzwYAG)

Integrations test error before implementing MMP fix with try-catch:
![test result before MMP fix with try catch](https://github.com/mulesoft/mule-maven-plugin/assets/97911932/afe44fc9-fbce-429c-8fd4-2800fdf4e41e)

Final Build :

2024-05-10 19:13 UTC, egrave requested changes

2024-05-13 18:35 UTC, aguozden commented on mule-extension-model-loader/src/main/java/org/mule/tooling/api/AstGenerator.java
> +      emptyPropertyResolverBuilder.withoutFailuresIfPropertyNotPresent();
Thanks Edu, I have reorder the code.

2024-05-14 16:47 UTC, WassimMelakhessou approved these changes
LGTM, I suggest requesting more reviews.

2024-05-14 18:30 UTC, egrave submitted a review, later dismissed

2024-05-14 20:30 UTC, aguozden commented
!gate waiver add Sonar

2024-05-14 20:31 UTC, egrave commented
!gate waiver add Sonar

2024-05-14 20:32 UTC, egrave approved these changes

2024-05-14 20:33 UTC, merged